server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          url-shortener:
            registration:
              client-id: "url-shortener"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/url-shortener"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: false
          swagger-ui:
            registration:
              client-id: "swagger-ui"
              client-secret: "{noop}swagger-secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client_credentials"
              scopes:
                - "read"
                - "write"

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger-ui
      client-secret: swagger-secret
      use-basic-authentication-with-access-code-grant: true
